### ISSUE TITLE
Add database indexes to deployments table

### ISSUE THREAD

**Issue by ngan** [peritor/webistrano#19]
Can you perhaps add indexes to the deployments table (and possibly others)?  After a lot of deployments, loading the stage page for a project takes a really really long time.

**Comment by jweiss** [comment]
Done with the latest commits

**Comment by ngan** [comment]
This actually didn't fix the issue.  Although adding indexes wouldn't hurt.  I've submitted a pull request that actually does fix this issue https://github.com/peritor/webistrano/pull/38
